# Generated by Django 5.0.6 on 2024-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_roommodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
